
jquery_lang_js.prototype.lang.it = {
	'County/Province': 'Regione / Provincia',
    'Join Us':  'Unisciti a noi',
    'Login': 'accesso',
    'Forgot Password': 'Hai dimenticato la password',
    'Show Map': 'Mostra mappa',
    'Welcome In Corporate Business World!':'Benvenuti nel mondo degli affari aziendali!',
    'Location:': 'Località:',
    'Town/City':'Località/città',
    'Category': 'categoria',
    'Submit':'presentare',
    'Login Page':'pagina di login',
    'Name:': 'Nome:',
    'Address 1:':'Indirizzo 1:',
    'Address 2:':'Indirizzo 2:',
    'State:': 'Stato:',
    'Phone:': 'Telefono:',
    'Date of Birth:' : 'Data di nascita:',
    'Password strength': 'della password',
    'Password not entered':'La password non è entrato',
    'Retype Password :': 'Conferma password:',
    'New User Registration':'Registrazione Nuovo Utente',
    'Pin:':'cerniera lampo:',
    'New User':'Nuovo utente',
    'My Listings': 'Indirizzo',
}